language: cpp
cache: apt

before_install:
   - sudo apt-get --yes update
   - sudo apt-get install --yes cmake

install:
  - git clone git://github.com/ninja-build/ninja.git && cd ninja
    git checkout release
    ./bootstrap.py > /dev/null 2>&1;
    sudo cp -v ninja /usr/bin/;
    cd ..;

script:
  - cd archer
  - ls
  - mkdir -p build
  - cd build
  - clang --version

notifications:
  slack: pruner:aXHVdiVFtqtMfzNW4IutZNDW
  email:
    recipients:
     - simone@cs.utah.edu
    on_success: always
    on_failure: always
